package com.shabinder.downloader.models.subtitles

import kotlin.jvm.JvmOverloads

class SubtitlesInfo @JvmOverloads constructor(
    url: String,
    val language: String,
    val isAutoGenerated: Boolean,
    val fromCaptions: Boolean = false
) {
    val url: String = url.replace(fmtRegex,"")  // existing format
        .replace(tlangRegex,"") // existing translation language

    val subtitles: Subtitles get() = Subtitles(url)

    override fun toString(): String {
        return "SubtitlesInfo($url,$language,$isAutoGenerated,$fromCaptions)"
    }

    companion object {
        private val fmtRegex = Regex("&fmt=[^&]*")
        private val tlangRegex = Regex("&tlang=[^&]*")
    }
}
